spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/susan_base?TimeZone=Asia/Shanghai
    username: susan
    password: susan@ht2013
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.sunjon.ScoreManager.bean
server:
  servlet:
    session:
      timeout: 60m
